<?php  if ( ! defined('BASE_PATH')) exit('No direct script access allowed');

/**
 * 例如：http://example.com/
*/
$config['base_url']	= '';

/*＊
 * 首页文件名
*/
$config['index_page'] = '';

/**
 * URI PROTOCOL
 *
 * This item determines which server global should be used to retrieve the
 * URI string.  The default setting of 'AUTO' works for most servers.
 * If your links do not seem to work, try one of the other delicious flavors:
 * 
 * 'AUTO'			Default - auto detects
 * 'QUERY_STRING'	Uses the QUERY_STRING	| http://hostname/dir[/entry.php]?dir=dir&class=class..
 * 'REQUEST_URI'	Uses the REQUEST_URI	| http://hostname/dir[/entry.php]/dir/class/method?query=name
 * 'CLI'			Uses the CLI			| php dir[/entry.php]dir/class/method ?query=value&query=value post=value
 */
$config['uri_protocol']	= 'AUTO';

/**
 * URL suffix
 *
 * This option allows you to add a suffix to all URLs generated by CodeIgniter.
 * For more information please see the user guide:
 */

$config['url_suffix'] = '';

/*
 * 默认语言包
 *
 * This determines which set of language files should be used. Make sure
 * there is an available translation if you intend to use something other
 * than english.
 *
*/
$config['default_language']	= 'zh';
$config['language']	= $config['default_language'];

/*
 * 语言包决定权：
 * 决定加载哪一个语言包的因素
 * 
 * cookie/session/segment/query
 * 关键字 lang
 * 如果是query，则仅在启用query的情况下有效
 * 如果是segment，则出现在 URI::segments[0]位置
 * 不填写则仅使用默认语言
 * 
 */
$config['language_decision'] = '';

/*
 * 默认输出编码
 *
 * This determines which character set is used by default in various methods
 * that require a character set to be provided.
 *
*/
$config['charset'] = 'UTF-8';

/*
 * Enable/Disable System Hooks
 *
 * If you would like to use the 'hooks' feature you must enable it by
 * setting this variable to TRUE (boolean).  See the user guide for details.
 *
*/
$config['enable_hooks'] = FALSE;


/*
 * Enable Query Strings
 *
 * By default CodeIgniter uses search-engine friendly segment based URLs:
 * example.com/who/what/where/
 *
 * By default CodeIgniter enables access to the $_GET array.  If for some
 * reason you would like to disable it, set 'allow_get_array' to FALSE.
 *
 * You can optionally enable standard query string based URLs:
 * example.com?who=me&what=something&where=here
 *
 * Options are: TRUE or FALSE (boolean)
 *
 * The other items let you set the query string 'words' that will
 * invoke your controllers and its functions:
 * example.com/index.php?c=controller&m=function
 *
 * Please note that some of the helpers won't work as expected when
 * this feature is enabled, since CodeIgniter is designed primarily to
 * use segment based URLs.
 *
*/
$config['controller_trigger']	= 'ctrl';
$config['function_trigger']		= 'func';
$config['directory_trigger']	= 'dir'; // experimental not currently in use

/*
 * Error Logging Threshold
 *
 * If you have enabled error logging, you can set an error threshold to
 * determine what gets logged. Threshold options are:
 * You can enable error logging by setting a threshold over zero. The
 * threshold determines what gets logged. Threshold options are:
 *
 *	0 = Disables logging, Error logging TURNED OFF
 *	1 = Error Messages (including PHP errors)
 *	2 = Debug Messages
 *	3 = Informational Messages
 *	4 = All Messages
 *
 * For a live site you'll usually only enable Errors (1) to be logged otherwise
 * your log files will fill up very fast.
 *
*/
$config['log_threshold'] = 0;

/*
 * Error Logging Directory Path
 *
 * Leave this BLANK unless you would like to set something other than the default
 * application/logs/ folder. Use a full server path with trailing slash.
 *
*/
$config['log_path'] = '';

/*
 * Date Format for Logs
 *
 * Each item that is logged has an associated date. You can use PHP date
 * codes to set your own date formatting
 *
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
 * Session Variables
 *
 * sess_driver			session 驱动程序，可选值：session, cookie, database, memcache
 * database 驱动需要有Session表和SessionModel支持
 *
*/
$config['sess_driver']			= 'database';
$config['sess_match_ip']		= FALSE;
$config['sess_expiration']		= 7200;
// cookie配置
$config['sess_cookie_name']		= 'ac_session';
$config['sess_encrypt_key']		= ''; // 8位
// memcache 配置
$config['sess_mem_host']		= 'ac_sessions';
$config['sess_mem_port']		= 'ac_sessions';

/*
 *--------------------------------------------------------------------------
 * Cookie Related Variables
 *--------------------------------------------------------------------------
 *
 * 'cookie_prefix' = Set a prefix if you need to avoid collisions
 * 'cookie_domain' = Set to .your-domain.com for site-wide cookies
 * 'cookie_path'   =  Typically will be a forward slash
 * 'cookie_secure' =  Cookies will only be set if a secure HTTPS connection exists.
 *
*/
$config['cookie_prefix']	= "";
$config['cookie_domain']	= "";
$config['cookie_path']		= "/";
$config['cookie_secure']	= FALSE;

/*
 * Global XSS Filtering
 *
 * Determines whether the XSS filter is always active when GET, POST or
 * COOKIE data is encountered
 *
*/
$config['global_xss_filtering'] = FALSE;

/*
 * Cross Site Request Forgery
 * 
 * Enables a CSRF cookie token to be set. When set to TRUE, token will be
 * checked on a submitted form. If you are accepting user data, it is strongly
 * recommended CSRF protection be enabled.
 *
 * 'csrf_token_name' = The token name
 * 'csrf_cookie_name' = The cookie name
 * 'csrf_expire' = The number in seconds the token should expire.
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;

/*
 * Output Compression
 *
 * Enables Gzip output compression for faster page loads.  When enabled,
 * the output class will test whether your server supports Gzip.
 * Even if it does, however, not all browsers support compression
 * so enable only if you are reasonably sure your visitors can handle it.
 *
 * VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
 * means you are prematurely outputting something to your browser. It could
 * even be a line of whitespace at the end of one of your scripts.  For
 * compression to work, nothing can be sent before the output buffer is called
 * by the output class.  Do not 'echo' any values with compression enabled.
 *
*/
$config['compress_output'] = FALSE;

/*
 * Master Time Reference
 *
 * Options are 'local' or 'gmt'.  This pref tells the system whether to use
 * your server's local time as the master 'now' reference, or convert it to
 * GMT.  See the 'date helper' page of the user guide for information
 * regarding date handling.
 *
*/
$config['time_zone'] = 'Asia/Harbin';

/*
 * Reverse Proxy IPs
 *
 * If your server is behind a reverse proxy, you must whitelist the proxy IP
 * addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
 * header in order to properly identify the visitor's IP address.
 * Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
 *
*/
$config['proxy_ips'] = '';
/*
 * 视图路径，如果需要放在子目录，则可以在此处填写。否则可以为空
 */
$config['view_path'] = 'default';
$config['view_ext'] = '.htm';

/*
 * 是否启用评测程序
 */
$config['enable_benchmark'] = FALSE;
/* Location: ./application/config/config.php */
